src_train_corpus_path: '${DATA_PATH}/train.en'
tgt_train_corpus_path: '${DATA_PATH}/train.ko'
src_valid_corpus_path: '${DATA_PATH}/dev.en'
tgt_valid_corpus_path: '${DATA_PATH}/dev.ko'
src_vocab_path: '${DATA_PATH}/tokenizer/en.vocab'
tgt_vocab_path: '${DATA_PATH}/tokenizer/ko.vocab'
num_vocabs: 32000
src_unk_symbol: 31999
tgt_unk_symbol: 31999
src_use_bos_symbol: True
src_use_eos_symbol: True
tgt_use_bos_symbol: True
tgt_use_eos_symbol: True
src_bos_symbol: 1
src_eos_symbol: 2
tgt_bos_symbol: 1
tgt_eos_symbol: 2
src_max_len: 100
tgt_max_len: 150
hidden_size: 512
num_heads: 8
num_encoder_layers: 6
num_decoder_layers: 6
dropout: 0.1
warm_up_steps: 4000
batch_size: 10000
total_steps: 150000
decode_max_length: 150
training_objective: 'smoothing_label'
smoothing_epsilon: 0.1
clip_gradient: 5.0
generator: 'beam_search'
beam_size: 3
